service:
  name: taskboard-backend

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: ${self:provider.stage}_task
            sources: [./migrations/tasks.json]
  appSync:
    name: appsync-serverless-sample
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ap-northeast-1
      userPoolId: ap-northeast-1_R7FtWWQ8g
      # スキーマ定義で認証設定が記述されていない場合の挙動を指定します
      # DENYを指定すると、認証されたいかなるユーザーも認可エラーに倒します
      # ALLOW 認証済ユーザーであれば、すべてのユーザーを許可する
      # DENY 認証済ユーザーであっても、すべてのユーザーを許可しない　※@aws_authを定義しないとアクセスできない
      defaultAction: ALLOW
    schema: schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: ${self:provider.stage}_task
        description: "タスク管理テーブル"
        config:
          tableName: { Ref: Table }
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
          region: ap-northeast-1
      # serverless-appsync-simulator では ローカルの Lambda 実行をサポートしていない？
      - type: AWS_LAMBDA
        name: version
        description: "Lambda DataSource for Version"
        config:
          functionName: version # The function name in your serverless.yml. Ignored if lambdaFunctionArn is provided.
          iamRoleStatements: # custom IAM Role statements for this DataSource. Ignored if `serviceRoleArn` is present. Auto-generated if both `serviceRoleArn` and `iamRoleStatements` are omitted
            - Effect: "Allow"
              Action:
                - "lambda:invokeFunction"
              Resource:
                - "*"
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: version
        type: Query
        field: version
        request: version.req.vtl
        response: version.res.vtl
      - type: Query
        field: getTask
        kind: PIPELINE
        request: "start.vtl"
        response: "end.vtl"
        functions:
          - getTask # 本当は使わなくて良いけど、関数の練習として書いてみる
      - dataSource: ${self:provider.stage}_task
        type: Query
        field: listTasks
        request: "listTasks.req.vtl"
        response: "listTasks.res.vtl"
      - dataSource: ${self:provider.stage}_task
        type: Mutation
        field: createTask
        request: "createTask.req.vtl"
        response: "end.vtl"
      - dataSource: ${self:provider.stage}_task
        type: Mutation
        field: updateTask
        request: "updateTask.req.vtl"
        response: "end.vtl"
      - dataSource: ${self:provider.stage}_task
        type: Mutation
        field: deleteTask
        request: "deleteTask.req.vtl"
        response: "end.vtl"
    functionConfigurations:
      - dataSource: ${self:provider.stage}_task
        name: "getTask"
        request: "getTask.req.vtl"
        response: "getTask.res.vtl"

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-dynamodb-local
  - serverless-appsync-simulator # must go before serverless-offline
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  profile: handson0001
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

# ref.: https://serverless.com/framework/docs/providers/aws/guide/packaging/#packaging-functions-separately
# package:
#   individually: true

functions:
  version:
    handler: src/functions/handler.version
    name: version
    events:
      - http: GET version

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}_task
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    AppSyncDynamoDBServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "dynamo-role"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "dynamo-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - "*"
